config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: "users#index"
  devise_for :users
  # get 'billing/index', to: 'billing#index'
  get '/card/new' => 'billings#new_card', as: :add_payment_method
  resources :billings
  resources :money_donators
  post "/card" => "billings#create_card", as: :create_payment_method
  get '/success' => 'billings#success', as: :success
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/money_donator.rb
class MoneyDonator < ApplicationRecord
  belongs_to :post
  validates :name, :contact_number, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :money_donators
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

    before_action :authenticate_user!

    def index
     @user=current_user.email
    end

    def new_card
        respond_to do |format|
          format.js 
        end
    end

    def create_card 
      respond_to do |format|
        if current_user.stripe_id.nil?
          customer = Stripe::Customer.create({"email": current_user.email}) 
          current_user.update(:stripe_id => customer.id)
        end
  
        card_token = params[:stripeToken]
        if card_token.nil?
          format.html { redirect_to billing_path, error: "Oops"}
        end
  
        customer = Stripe::Customer.new current_user.stripe_id
        customer.source = card_token
        customer.save
  
        format.html { redirect_to success_path }
      end
    end

    def success
    end


end

app/controllers/money_donators_controller.rb
class MoneyDonatorsController < ApplicationController
    
    def new
        post = Post.find(params[:post])
        @donator = MoneyDonator.new(post: post)
    end

    def create
        post = Post.find_by(id: params[:money_donator][:post_id])
        @donator = post.money_donators.create(donator_params)
        if @donator.save!
            redirect_to billings_path()
            flash[:notice] = "Donator Saved Sucessfully"
        else
            flash[:notice] = "Donator not saved"
        end
    end

    def redirect_search
        "window.location.href='"+add_payment_method_path+"'"
    end

private

    def donator_params
        params.require(:money_donator).permit(:name, :contact_number, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @posts = Post.all
  end


  def show
    
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/money_donators_helper.rb
module MoneyDonatorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/billings/index.html.erb
<body class="body-color">
<%= form_tag create_payment_method_path, id: "billing-create-payment-method" do  %>
  <%= link_to "Let's go", add_payment_method_path, remote: true, class: "btn btn-primary", id: "button-moving" %>
<% end %>

<p class="moving-text">Please Click On the Link For Donating Money!!</p>
</body>

app/views/billings/new_card.js.erb
var handler = StripeCheckout.configure({
    key: 'pk_test_cL8NyqvMzkCPLT75bKiRMt7u00hXknWUEP',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "upload.express",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        var form = document.getElementById('billing-create-payment-method');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card 
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});

app/views/billings/success.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h2>You successfully linked a credit card to your account</h2>
      <h3>Congratulations!!</h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/money_donators/_form.html.erb
  <%= form_for [@donator], :html => { :class => "form-horizontal donator" } do |f| %>

    <% if @donator.errors.any? %>
      <div id="error_explanation" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(donator.errors.count, "error") %> prohibited this donator from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @donator.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :contact_number, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :contact_number, :class => 'form-control' %>
      </div>
      <%= f.hidden_field :post_id, value: @donator.post_id %>
      <%=f.error_span(:contact_number) %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  
  <% end %>
  

app/views/money_donators/new.html.erb
<h1>New Donator</h1>

<%= render 'form', donator: @donator %>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

  <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t 'Social Contributor' %></h1>
<% if current_user %>
<%= link_to t('.Sign Out', :default => t("helpers.links.Sign Out")),
  destroy_user_session_path, method: :delete,
    :class => 'btn btn-primary' %>
  <% else %>
  <%= link_to t('.new registration', :default => t("helpers.links.new registration")),
  new_user_registration_path,
    :class => 'btn btn-primary' %> |
  <%= link_to t('.Sign In', :default => t("helpers.links.Sign In")),
  new_user_session_path,
    :class => 'btn btn-primary' %>
  <% end %>  
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:Email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.user.email %></td>
        <td><%=l post.created_at %></td>
        <td><%= link_to t('.Show', :default => t("helpers.links.Show")),
        post, :class => 'btn btn-primary btn-xs' %></td>
        <% if current_user && current_user.admin? || post.user == current_user %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_post_path(post), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        post_path(post),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t 'Social Involvement', :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @post.user.email %></dd>
</dl>

<%= link_to t('.donation', :default => t("helpers.links.donation")),
              new_money_donator_path(:post => @post.id), :class => 'btn btn-primary'  %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<% if current_user && current_user.admin? || @post.user == current_user %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_post_path(@post), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                post_path(@post),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>

app/views/users/index.html.erb
<h1 class="margin-class-header">Alpha Blog</h1>

<div class="move-button">
    <% if current_user %>
    <%= link_to t('.Sign Out', :default => t("helpers.links.Sign Out")),
    destroy_user_session_path, method: :delete,
        :class => 'btn btn-primary' %>
    <% else %>
    <%= link_to t('.new registration', :default => t("helpers.links.new registration")),
    new_user_registration_path,
        :class => 'btn btn-primary' %> |
    <%= link_to t('.Sign In', :default => t("helpers.links.Sign In")),
    new_user_session_path,
        :class => 'btn btn-primary' %>
    <% end %> |  

    <%= link_to t('.Post', :default => t("helpers.links.Post")),
    posts_path,
        :class => 'btn btn-primary .btn-mini' %>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <h3>About</h3>
            <p>Social work is an academic discipline and profession that concerns itself with individuals, families, groups, and communities in an effort to enhance social functioning and overall well-being.[1][2] Social functioning is the way in which people perform their social roles, and the structural institutions that are provided[by whom?] to sustain them.[3] Social work applies social sciences, such as sociology, psychology, political science, public health, community development, law, and economics, to engage with client systems, conduct assessments, and develop interventions to solve social and personal problems; and to bring about social change. Social work practice is often divided into micro-work, which involves working directly with individuals or small groups; and macro-work, which involves working with communities, and - within social policy - fostering change on a larger scale.[4]<p>
            <em>“Social work is a practice-based profession and an academic discipline that promotes social change and development, social cohesion, and the empowerment and liberation of people. Principles of social justice, human rights, collective responsibility and respect for diversities are central to social work. Underpinned by theories of social work, social sciences, humanities, and indigenous knowledge, social work engages people and structures to address life challenges and enhance well-being."[8] –International Federation of Social Workers.</em>
            <p>Social work practice consists of the professional application of social work values, principles, and techniques to one or more of the following ends: helping people obtain tangible services; counseling and psychotherapy with individuals, families, and groups; helping communities or groups provide or improve social and health services, and participating in legislative processes. The practice of social work requires knowledge of human development and behavior; of social and economic, and cultural institutions; and the interaction of all these factors."[10] –National Association of Social Workers

            Social workers work with individuals and families to help improve outcomes in their lives. This may be helping to protect vulnerable people from harm or abuse or supporting people to live independently. Social workers support people, act as advocates and direct people to the services they may require. Social workers often work in multi-disciplinary teams alongside health and education professionals.[14]</p>
            <p>This was accompanied by a less easily defined movement; the development of institutions to deal with the entire range of social problems. All had their most rapid growth during the nineteenth century, and laid the foundation basis for modern social work, both in theory and in practice.[15]

            Professional social work originated in 19th century England, and had its roots in the social and economic upheaval wrought by the Industrial Revolution, in particular, the societal struggle to deal with the resultant mass urban-based poverty and its related problems. Because poverty was the main focus of early social work, it was intricately linked with the idea of charity work.[15]  Other important historical figures that shaped the growth of the social work profession are Jane Addams, who founded the Hull House in Chicago and won the Nobel Peace Prize in 1931; Mary Ellen Richmond, who wrote Social Diagnosis, one of the first social workbooks to incorporate law, medicine, psychiatry, psychology, and history; and William Beveridge, who created the social welfare state, framing the debate on social work within the context of social welfare provision.</p>
                <a class="btn btn-primary btn-large">
                Learn more
                </a>
            </p>
    </div>
</div>